Updating docker images

diff --git a/r/Dockerfile b/r/Dockerfile
--- a/r/Dockerfile
+++ b/r/Dockerfile
@@ -1,14 +1,13 @@
-FROM ubuntu:xenial
+FROM debian:jessie
 
+ARG R_VERSION
+ARG BUILD_DATE
+ENV R_VERSION ${R_VERSION:-3.4.0}
+ENV LC_ALL en_US.UTF-8
+ENV LANG en_US.UTF-8
+ENV TERM xterm
 
-# Ubuntu house cleaning
-RUN apt-get update \
-  && apt-get install -y --no-install-recommends \
-  software-properties-common \
-  apt-transport-https
-
-
-## Install dependencies
+## dependencies
 RUN apt-get update \
   && apt-get install -y --no-install-recommends \
     bash-completion \
@@ -20,6 +19,8 @@ RUN apt-get update \
     gsfonts \
     libbz2-1.0 \
     libcurl3 \
+    libicu52 \
+    libjpeg62-turbo \
     libopenblas-dev \
     libpangocairo-1.0-0 \
     libpcre3 \
@@ -31,7 +32,10 @@ RUN apt-get update \
     unzip \
     zip \
     zlib1g \
-    curl \
+  && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
+  && locale-gen en_US.utf8 \
+  && /usr/sbin/update-locale LANG=en_US.UTF-8 \
+  && BUILDDEPS="curl \
     default-jdk \
     libbz2-dev \
     libcairo2-dev \
@@ -58,14 +62,64 @@ RUN apt-get update \
     xauth \
     xfonts-base \
     xvfb \
-    zlib1g-dev
-
-# Install R base
-RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9 \
-  && add-apt-repository 'deb [arch=amd64,i386] https://cran.rstudio.com/bin/linux/ubuntu xenial/'\
-  && apt-get update \
-  && apt-get install -y --no-install-recommends \
-  r-base
+    zlib1g-dev" \
+  && apt-get install -y --no-install-recommends $BUILDDEPS \
+  && cd tmp/ \
+  ## Download source code
+  && curl -O https://cran.r-project.org/src/base/R-3/R-${R_VERSION}.tar.gz \
+  ## Extract source code
+  && tar -xf R-${R_VERSION}.tar.gz \
+  && cd R-${R_VERSION} \
+  ## Set compiler flags
+  && R_PAPERSIZE=letter \
+    R_BATCHSAVE="--no-save --no-restore" \
+    R_BROWSER=xdg-open \
+    PAGER=/usr/bin/pager \
+    PERL=/usr/bin/perl \
+    R_UNZIPCMD=/usr/bin/unzip \
+    R_ZIPCMD=/usr/bin/zip \
+    R_PRINTCMD=/usr/bin/lpr \
+    LIBnn=lib \
+    AWK=/usr/bin/awk \
+    CFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g" \
+    CXXFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g" \
+  ## Configure options
+  ./configure --enable-R-shlib \
+               --enable-memory-profiling \
+               --with-readline \
+               --with-blas="-lopenblas" \
+               --disable-nls \
+               --without-recommended-packages \
+  ## Build and install
+  && make \
+  && make install \
+  ## Add a default CRAN mirror
+  && echo "options(repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site \
+  ## Add a library directory (for user-installed packages)
+  && mkdir -p /usr/local/lib/R/site-library \
+  && chown root:staff /usr/local/lib/R/site-library \
+  && chmod g+wx /usr/local/lib/R/site-library \
+  ## Fix library path
+  && echo "R_LIBS_USER='/usr/local/lib/R/site-library'" >> /usr/local/lib/R/etc/Renviron \
+  && echo "R_LIBS=\${R_LIBS-'/usr/local/lib/R/site-library:/usr/local/lib/R/library:/usr/lib/R/library'}" >> /usr/local/lib/R/etc/Renviron \
+  ## install packages from date-locked MRAN snapshot of CRAN
+  && [ -z "$BUILD_DATE" ] && BUILD_DATE=$(TZ="America/Los_Angeles" date -I) || true \
+  && MRAN=https://mran.microsoft.com/snapshot/${BUILD_DATE} \
+  && echo MRAN=$MRAN >> /etc/environment \
+  && export MRAN=$MRAN \
+  ## MRAN becomes default only in versioned images
+  ## Use littler installation scripts
+  && Rscript -e "install.packages(c('littler', 'docopt'), repo = '$MRAN')" \
+  && ln -s /usr/local/lib/R/site-library/littler/examples/install2.r /usr/local/bin/install2.r \
+  && ln -s /usr/local/lib/R/site-library/littler/examples/installGithub.r /usr/local/bin/installGithub.r \
+  && ln -s /usr/local/lib/R/site-library/littler/bin/r /usr/local/bin/r \
+  ## Clean up from R source install
+  && cd / \
+  && rm -rf /tmp/* \
+  # && apt-get remove --purge -y $BUILDDEPS \
+  && apt-get autoremove -y \
+  && apt-get autoclean -y \
+  && rm -rf /var/lib/apt/lists/*
 
 # Update R java conf
 RUN R CMD javareconf
@@ -86,3 +140,5 @@ RUN apt-get update -qq && apt-get -y --no-install-recommends install \
   libgdal1-dev \
   libproj-dev \
   && Rscript -e 'install.packages(c("rgdal", "rJava", "bcrypt", "shiny", "rmarkdown", "knitr",  "shinydashboard", "data.table", "mailR", "shinyjs", "DT", "leaflet", dependencies = TRUE), repos = "https://cran.rstudio.com")'
+
+CMD ["R"]
